### ISSUE TITLE
getUpdates parameters

### ISSUE THREAD

**Issue by Welsyntoffie** [codingsett/telepota#3]
No discussion board, so posting here.
I noticed that this library uses 4.5MB per hour on my metered mobile connection, which is way to high.
So I attempted to modify the getUpdates parameters.
In your library...
```
    def run_forever(self, relax=0.1, offset=None, timeout=20, allowed_updates=None):
        """
        Process new updates in infinity loop
        :param relax: float
        :param offset: int
        :param timeout: int
        :param allowed_updates: **bool**
```
allowed_updates is bool but according to api docs should be an array of string?

Anyway, I tried relax=7, timeout=60 and allowed_updates=["message"], but data usage is still over 3.6MB per hour.
I am using 1 script only looping and checking usage with nethogs and vnstat. Wifi connection on ubuntu 20.04 has been set to metered. If I stop the script no data is consumed.
Is there another way I should try to lower the data usage?

**Comment by codingsett** [comment]
Thanks for pointing out the bugs in the docs.

Since by default the library is using long polling it tends to use more bandwidth.

I would suggest using webhooks which are also supported by this library.

**Comment by Welsyntoffie** [comment]
Thanks, webhooks is a bit extra effort I dont want to spend time on now.

I did a fresh install of ubuntu 20.04, installed only this library and pylogix. Relax=7 and timeout=20.
Data usage is now less than 5MB per day. average around 200KB per hour soem more some times less.
Must have been something that attached to the python instance.
