### ISSUE TITLE
Major differences to telepot

### ISSUE THREAD

**Issue by skjerns** [codingsett/telepota#7]
After reading #4 I have another question:

What are the main differences to telepot? Are there any advantages? So far I have a legacy bot with matched methods to still make it work well with the newer API changes. Are there any advantages to `telepot`?

Is there any actively-developed telepot fork or do I eventually need to recode the bot in an active framework?

**Comment by codingsett** [comment]
The main difference is this fork is ahead with new functions compared to the previous one. If you want new features to be added rapidly as they are released then it would not suitable to use this library
